[phases.setup]
nixPkgs = ["tesseract", "poppler_utils", "curl"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "python start.py"
